const GITHUB_AUTH_TOKEN = "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"
const GITHUB_USERNAME = "athulakumara604"
const SESSION_ID = "XQs0iboB#objco8S0ld31ihw4Z3YvJTc1EZgO57TJvmY8i_BJ8Jo"


module.exports = {
GITHUB_AUTH_TOKEN,
GITHUB_USERNAME,
SESSION_ID
}
